name: streamlit-app
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8  # Specify Python 3.8
  - pip
  - pip:
      - streamlit==1.38.0
      - snowflake-connector-python==3.12.2
      - snowflake-snowpark-python==1.22.1
      - snowflake-ml-python==1.6.2
      - snowflake.core==0.12.1
     # - snowflake.cortex==0.42.1
      - transformers==4.44.2
      # Add any additional pip packages here
