default_connection_name = "SF_Dinesh2012"

[SF_Dinesh2012]
account = "jib04181"
user = "dinesh2012"
password = "Din143@doc1"
database = "CORTEX_SEARCH_TUTORIAL_DB"
schema = "PUBLIC"
warehouse = "CORTEX_SEARCH_TUTORIAL_WH"
role = "ACCOUNTADMIN"

[cli.logs]
save_logs = true
path = "C:\\Users\\~DINESH~\\AppData\\Local\\snowflake\\logs"
level = "info"
